name: DevOps Group 7 CI/CD

on:
  push:
    branches: [ "main", "release" ]
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn -B clean install -DskipTests
      - run: mvn -B test
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  integration-tests:
    runs-on: ubuntu-22.04
    needs: unit-tests
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: P@ssw0rd!
          MYSQL_DATABASE: world
        ports: [ "33060:3306" ]
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -pP@ssw0rd!"
          --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: |
          for i in {1..30}; do
            mysql -h127.0.0.1 -P33060 -uroot -pP@ssw0rd! -e "SELECT 1;" && break
            sleep 2
          done
      - run: mysql -h127.0.0.1 -P33060 -uroot -pP@ssw0rd! world < world-db/world.sql
      - run: mvn -B verify

  build:
    runs-on: ubuntu-22.04
    needs: [unit-tests, integration-tests]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn -B package -DskipTests
      - run: docker build -t webapp:${{ github.sha }} .
      - run: docker compose up --abort-on-container-exit --build
