name: A workflow for DevOps Group 7

on: push

jobs:
  UnitTests:
    name: Unit Test Build Action
    runs-on: ubuntu-22.04

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: P@ssw0rd!
          MYSQL_DATABASE: world
        ports:
          - "33060:3306"
        volumes:
          - db_data:/var/lib/mysql
          - ./world-db:/docker-entrypoint-initdb.d:ro
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -pP@ssw0rd!"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Unit Tests
        run: mvn -Dtest=com.napier.devops.AppTest test
      - name: List dirs
        run: |
          cd ./target/ 
          pwd
          ls
      - name: CodeCov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  Build:
    name: Devops Group7 Build Actions
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # If you need Java build first (Maven/Gradle)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Build the Docker image for the webapp
      - name: Build webapp container
        run: docker build -t webapp:latest .

      # Run docker compose and wait for containers to finish
      - name: Run docker compose
        run: docker compose up --abort-on-container-exit --build
